### ISSUE TITLE
EPIC: review first major contributions to woltka

### ISSUE THREAD

**Issue by gwarmstrong** [qiyunzhu/woltka#14]
This issue is to keep track of files that have been reviewed as a part of the first major review of woltka. This may take place over several reviews and PR's. This issue should remain open until all the major files have been reviewed.

### TODO

- [ ] overall design
- [ ] command-line interfaces
    - [x] `cli.py`
    - [ ] `q2` 
- [ ] `classify.py` (classification workflow)
~~- [ ] `sample.py` (sample & file parser) (simple)~~ `sample.py` deleted in 2a583d7319cf0a6e17a2a960c0ab6e70ff60bb9f
- [ ] `align.py` (alignment parser)
- [ ] `tree.py` (classification system)
- [ ] `ordinal.py` (gene-read matching) (low priority)
- [x] `util.py` (generic utilities)
- [ ] documentation
    - [x] README.md
- [x] `workflow.py`

Fixes #8
